### ISSUE TITLE
Truncated tags

### ISSUE THREAD

**Issue by jpalaciosdev** [HessiJames/soundkonverter#20]
soundKonverter version: 2.1.2

In some circumstances, when a tag includes the substring " - ", the tag is truncated at the start of that substring. This happens always if some punctuation characters are present in the preceding string.
For example, in the string "Title: this part is included - This is not included", the substring " - This is not included" is not transferred to the destination tag of the converted file.
I created a test file with some tags (download it from here [1]). Please, note that in this case, the tag 'ALBUM' is also affected, although there are no other precedent punctuation symbols.

[1] https://dl.dropboxusercontent.com/u/66933796/test.flac

**Comment by HessiJames** [comment]
Thanks, but this is a taglib issue, so I reported it there.
