### ISSUE TITLE
webm (opus)

### ISSUE THREAD

**Issue by Ray-Ven** [HessiJames/soundkonverter#28]
It seems, SoundKonverter can't find the opus part in an webm file - would be very nice though! I use soundkonverter very often to get the audio out of a video. I know, it can be done with audacity or so - but I really love soundkonverter - it's so easy to use

Thank you

**Comment by HessiJames** [comment]
Could you point me to such a webm file?

**Comment by Ray-Ven** [comment]
I've uploaded one at my ownlcloud:
https://rayscloud.mooo.com/owncloud/index.php/s/kCtVXPX7D5JUIsP
you can get them for example on youtube.

Thank you for soundkonverter!! We really love it!


Am Tuesday 19 January 2016, 08:46:12 schrieb Daniel Faust:

**Comment by HessiJames** [comment]
Fixed with commit 270f8fc.

**Comment by Ray-Ven** [comment]
awesome!
