### ISSUE TITLE
FFmpeg libvorbis support not recognised on Arch Linux

### ISSUE THREAD

**Issue by argymeg** [HessiJames/soundkonverter#29]
Although FFmpeg is compiled with libvorbis support, soundKonverter does not recognise it. The only way to enable vorbis support with FFmpeg is to enable experimental codecs, which I assume uses the internal codec which is not recommended.
![spectacle j27392](https://cloud.githubusercontent.com/assets/7372767/12378082/01b85e0c-bd3c-11e5-9fd4-bfd508cceda8.png)
![spectacle j27420](https://cloud.githubusercontent.com/assets/7372767/12378083/01dc215c-bd3c-11e5-9e18-f5a59342d522.png)

**Comment by HessiJames** [comment]
Could you post the output of "ffmpeg -codecs"?

**Comment by argymeg** [comment]
I already have, it's the second image right below the first screenshot.

**Comment by HessiJames** [comment]
The screenshot only show the compilation options, I need the listing of all supported codecs.
Run "ffmpeg -codecs > ffmpeg_codecs" and then attach the file ffmpeg_codecs.

**Comment by argymeg** [comment]
D' oh. My bad.
[ffmpeg_codecs.txt](https://github.com/HessiJames/soundkonverter/files/96875/ffmpeg_codecs.txt)

**Comment by HessiJames** [comment]
Should be fixed with commit 01b902e.
