### ISSUE TITLE
Remember status of 'calculate replay gain tags'

### ISSUE THREAD

**Issue by kokosowy** [HessiJames/soundkonverter#36]
Hi,

I need to keep selecting this 'calculate replay gain tags' option every time I rip CD. Can't we set it somewhere as remembered preference?

Many thanks,
K

**Comment by HessiJames** [comment]
This should actually work. Is the "standard profile" in the config dialog set to "lats used"?

**Comment by kokosowy** [comment]
I will make sure today and let you know. Thanks.

**Comment by kokosowy** [comment]
I've just ensured. I have 'last used' option selected in config. It remembers all but 'calculate replay gain tags' setting. It's always deselected by default. v2.2.0 Thanks.

**Comment by kokosowy** [comment]
This is still happening in v2.2.2

**Comment by kokosowy** [comment]
After fresh installation of OS and application it seems it remembers this option now. Probably some remains from previous configuration made it not working for me previously, but not sure.
