### ISSUE TITLE
UI languages

### ISSUE THREAD

**Issue by kokosowy** [HessiJames/soundkonverter#37]
Hi again,

I can see that many languages (including Polish) are available through Transifex service. Why these are not included in SoundKonverter or cannot be used? I can't see any option for that.

Thanks.

Kind regards,
K

**Comment by HessiJames** [comment]
Your are right, the polish translation is not included yet, I will change that.

**Comment by kokosowy** [comment]
Thank you! I'm wondering, maybe other translations are missing as well. Worth checking.

**Comment by kokosowy** [comment]
Thank you so much! 

K
