### ISSUE TITLE
Player button always plays track #1

### ISSUE THREAD

**Issue by kokosowy** [HessiJames/soundkonverter#39]
Hi again,

I've noticed no matter which player (preview) button I will press always track number one is starting for hearing.

v2.2.0

Kind regards,
K

**Comment by HessiJames** [comment]
Works fine for me.
The only thing I can think of right now that could cause this is the phonon back-end. I use the gstreamer back-end. And I'm talking about the qt4 version of phonon.

**Comment by kokosowy** [comment]
Hmm.. I'm not sure how to approach this.. Soon I will reinstall my system with Linux Mint 18 (KDE flavour, based on Ubunbu 16.04 LTS) and will confirm.

**Comment by HessiJames** [comment]
Well you may upgrade your system of cause but I don't think that it will do anything about this problem.
http://packages.ubuntu.com/search?keywords=phonon&searchon=names&suite=xenial&section=all shows that there is libphonon4 and libphonon4qt5. soundkonverter is using the former.
There are two back-ends for libphonon4: phonon-backend-gstreamer and phonon-backend-vlc
If you have phonon-backend-vlc istalled, remove it and install phonon-backend-gstreamer.

**Comment by kokosowy** [comment]
I will give it a try. I will reinstall system anyway later on. However it'd be good having SoundKonverter compatible with current distributions versions out of the box, not sure how tricky that would be.

**Comment by kokosowy** [comment]
System reinstalled, latest release compiled, SK configured, problem is no more. Thanks.

**Comment by HessiJames** [comment]
Good. Thanks for letting me know.
