### ISSUE TITLE
Frequency modulation (FM)

### ISSUE THREAD

**Issue by MichaelZP** [HessiJames/soundkonverter#41]
How to modulate one waveform/track with another to achieve FM(Freq. Modulation)?
![fm_](https://cloud.githubusercontent.com/assets/17249917/16712012/ed8aaab8-4678-11e6-9b67-4c44ac081e7f.jpg)

**Comment by HessiJames** [comment]
Sorry, but that's not something soundkonverter does. This sounds like a problem for a sound editor (like audacity). Please reopen in case I misunderstood you.
